In [43]:
import pandas as pd
import numpy as np
import numexpr as ne

In [63]:
predicted = np.matrix([[0.4, 0.7, 0.7, 0.2], [0.6, 0.3, 0.3, 0.8]])

true = np.matrix([[0, 1], [0, 1], [0, 1], [1,0]])

print predicted.shape
print true.shape

print predicted
print true.T

(2L, 4L)
(4L, 2L)
[[ 0.4  0.7  0.7  0.2]
 [ 0.6  0.3  0.3  0.8]]
[[0 0 0 1]
 [1 1 1 0]]


In [75]:
predicted_max = np.argmax(predicted, axis = 0)

true_max = np.argmax(true, axis = 1)

print predicted_max
print true_max.T

print predicted_max.shape

[[1 0 0 1]]
[[1 1 1 0]]
(1L, 4L)


In [65]:
N = true_max.shape[0]
number_true = np.dot(predicted_max, true_max)

print number_true

[[1]]


In [66]:
print N

print number_true * 1.0/N

4
[[ 0.25]]


In [67]:
ne.evaluate('(true_max == 0) & (predicted_max == 0)').astype(int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 1, 0]])

In [74]:

class_acc = np.sum(np.all(true_max.T == predicted_max, axis = 0)) * 1.0 / N
class_err = np.sum(np.all(true_max.T != predicted_max, axis = 0)) * 1.0 / N

np.sum(np.all((true_max.T == 0) & (predicted_max == 0), axis = 0)) 

np.sum(np.all((true_max.T == 1) & (predicted_max == 0), axis = 0)) 

np.sum(np.all((true_max.T == 1) & (predicted_max == 0), axis = 0)) 

print(class_err, class_acc)

(0.75, 0.25)
